#!/usr/bin/env ansible-playbook

- hosts: all
  become: yes
  gather_facts: yes
  vars:
    users: 1
    slaves: 1
    cidr: "172.18.1.1/20"
  tasks:
    - name: Baseline Machine
      yum: name={{ item }} state=present
      with_items:
        - docker
        - python-pip
        - python-docker-py
      tags:
        - baseline
